# PAM module configuration for Okta Device Flow authentication
# File must be owned by root and not world-readable (chmod 600).

device_authorize_url = https://dev-57525606.okta.com/oauth2/v1/device/authorize
token_url            = https://dev-57525606.okta.com/oauth2/v1/token
client_id            = 0oa15wulqt5yqD9FP5d7
